[mcp_servers.github-mcp-server]
command = "docker"
args = [ "run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server",]
id = ""

[mcp_servers.context7]
command = "docker"
args = [ "run", "-i", "--rm", "-e", "CONTEXT7_API_KEY", "mcp/context7",]
id = ""

[mcp_servers.github-mcp-server.env]

[mcp_servers.context7.env]
