services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        RAILS_ENV: development
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SETTINGS__DATABASE__HOST: db
      SETTINGS__DATABASE__PORT: 5432
    networks:
      - default
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rails8todo.rule=Host(`todo.localhost`)"
      - "traefik.docker.network=dev-proxy"
      - "traefik.http.services.rails8todo.loadbalancer.server.port=3000"

volumes:
  db_data:
    driver: local

networks:
  dev-proxy:
    external: true
