default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
  database: <%= Settings.database.name %>
  host: <%= Settings.database.host %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development: &development
  <<: *default
  port: <%= Settings.database.port %>
  database: <%= Settings.database.name %>_development

test:
  <<: *development
  port: <%= Settings.database.port %>
  database: <%= Settings.database.name %>_test<%= ENV.fetch('TEST_ENV_NUMBER', '') %>

staging:
  <<: *default

production:
  <<: *default
  url: <%= Settings.database.url %>
